### PR TITLE
docs: add note about overriding ddev version when debugging go

### PR DESCRIPTION
**Pull request by hanoii**

### CODE REVIEW

**Review by rfay — APPROVED** [review]
Thanks, looks great!

**Comment by hanoii** [comment]
let me add something

**Comment by hanoii** [comment]
Done!

**Comment by hanoii** [comment]
It's good!

**Comment by rfay** [comment]
Oh, one tiny thing, please change the updated date.

**Comment by hanoii** [comment]
Done!

**Comment by rfay** [comment]
Thanks so much!

**Pull request merged**
