### PR TITLE
Add NodeJS tutorial by Andy Blum to Vite article

### PR DESCRIPTION
**Pull request by mandrasch**
Add awesome article https://www.lullabot.com/articles/nodejs-development-ddev to the list of examples mentioned in https://ddev.com/blog/working-with-vite-in-ddev/

### CODE REVIEW

**Review by rfay — APPROVED** [review]
Thanks!

**Comment by rfay** [comment]
Trying to figure out why tests failed.

**Comment by mandrasch** [comment]
> Trying to figure out why tests failed.

Strange, I found only something like this https://github.com/actions/setup-node/issues/694. Maybe upgrading `actions/setup-node@v3` to `actions/setup-node@v4` and also upgrading to `actions/checkout@v4` might help?

**Comment by mandrasch** [comment]
Or setting the package manager explicitly for https://github.com/withastro/action? But should be autodetected ...

```
uses: withastro/action@v2
        with:
            path: . # The root location of your Astro project inside the repository. (optional)
            node-version: 20 # The specific version of Node that should be used to build your site. Defaults to 18. (optional)
            package-manager: npm@latest
```

**Comment by stasadev** [comment]
Rebased after fixing tests.

**Pull request merged**
