### PR TITLE
Fixes DDEV search component.

### PR DESCRIPTION
**Pull request by bmartinez287**
## The Issue
The issue is described here
* https://github.com/ddev/ddev.com/issues/146

## How This PR Solves The Issue
It adds the domain to the javascript search utility.

### CODE REVIEW

**Comment by bmartinez287** [comment]
After looking at a few alternatives such as creating a constant, or saving the domain on the search.json file this seemed to be the quickest and potentially the most elegant fix. @rfay

**Review by rfay — APPROVED** [review]
Well, it sure works and it sure seems elegant! Thanks.

**Comment by bmartinez287** [comment]
I will merge it in since it's already broken, but if you have a suggestion for a fix that's a bit better let us know. @mattstein. I think it originally worked because it made some assumptions that the recent major upgrade took away.

**Comment by rfay** [comment]
OK, sounds like a plan. We can go back to it if Matt has a better idea.

**Comment by bmartinez287** [comment]
No worries, thanks for keeping the project up to date.

**Pull request merged**
