### PR TITLE
Add DDEV store links.

### PR DESCRIPTION
**Pull request by bmartinez287**
## The Issue
Adds the DDEV store links to ddev.com

### CODE REVIEW

**Review by rfay — CHANGES_REQUESTED** [review]
I like this, but I'm not really good with putting the store in the header, it's too important a space. Footer OK, other ideas OK, blog OK.

**Comment by bmartinez287** [comment]
Sounds good, thoughts on renaming it from shop to swag shop?
https://astro.build/
Screenshot 2024-03-11 at 12 26 07 PM
Like astro does?

**Comment by rfay** [comment]
"Swag shop" is clearer and fine with me.

**Review by rfay — APPROVED** [review]
Looks ok to me, thanks!

**Comment by bmartinez287** [comment]
relates https://github.com/ddev/ddev/issues/5792

**Pull request merged**
