### PR TITLE
Promote training sessions

### PR DESCRIPTION
**Pull request by tyler36**
This PR improves the visibility of the training sessions by:

- adding link in footer to blog post.
- adding a section on the contributing page.

### CODE REVIEW

**Comment by tyler36** [comment]
I think the past training links, future training links, and sign up form would be better suited on the contributing page instead of in a past blog post. The contributing page would then be updated moving forward. Thoughts?

**Comment by rfay** [comment]
I agree that in the future we should probably have a better place for this in general.

**Comment by mattstein** [comment]
I took a run at a dedicated page [over here](https://github.com/ddev/ddev.com/pull/73) before I realized I was probably overthinking it when the eternally-updated blog post seemed to be going okay.

**Comment by rfay** [comment]
We're probably near the end of the run for this set of training sessions anyway, only one more is currently scheduled, so maybe next time we'll do it the right way.

**Pull request merged**
