### PR TITLE
Prepare a new set of contributor trainings

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

It's time to restart contributor training. 

Prepare a list and schedule!

### CODE REVIEW

**Comment by tyler36** [comment]
Ooohhhh .... looking forward to these!

**Comment by stasadev** [comment]
This is a great list!

It would be useful (especially for beginners) to know more about git, branch naming, conventions used for PR, why we squash commits (and how to configure repo for this), why we don't use merge, how to resolve conflicts on the rebase, how to checkout another user's branch and not get lost in multiple remote origins, etc.

I have no priorities regarding the order of trainings.

**Comment by tyler36** [comment]
Re-post my DM for discussion:

The training sessions look good. Random musing:

- https://github.com/ddev/ddev/issues/5740 might make a good session for creating a command, or addon
- xdebug training sooner; always seems to be support questions
- session on extracting "share" into a global command (so devs can alter it they want a "different" provider)

What about "lightning" sessions? Say, 5 minute demo on a particular feature? 

- Using ddev snapshot
- Push and pull files/db with a provider
- Using DDEV on any Github repo (bookmarklet, https://ddev.github.io/ddev-gitpod-launcher/)
- github-action-setup-ddev

**Comment by rfay** [comment]
> What about "lightning" sessions? Say, 5 minute demo on a particular feature?

Using ddev snapshot
Push and pull files/db with a provider
Using DDEV on any Github repo (bookmarklet, https://ddev.github.io/ddev-gitpod-launcher/)
github-action-setup-ddev

I'd like to do things like this as leaders on Office Hours sessions, would be fantastic.

**Pull request merged**
