### PR TITLE
Add npm run build to the ci test.

### PR DESCRIPTION
**Pull request by bmartinez287**
## The Issue
The build might fail crashing the site.

## How This PR Solves The Issue

Add npm run build to the ci test.

### CODE REVIEW

**Review by rfay — APPROVED** [review]
Awesome, thanks!

**Review by rfay — CHANGES_REQUESTED** [review]
I guess we'll have to provide a token to make this work. Or figure out how to skip all the image stuff. Or just do the `npm run dev` ?

**Comment by rfay** [comment]
This only takes a token that has no power at all. There should be a way to do it!

**Comment by rfay** [comment]
I think we should just be able to just provide the $GITHUB_TOKEN from the *forked* PR to the workflow and it would be adequate for this. Not sure.

**Comment by rfay** [comment]
I think this just worked!

**Review by rfay — APPROVED** [review]
Seems like we have it here! If you like it pull it.

**Comment by rfay** [comment]
This may still fail with forked PRs. Let's get it in and then we'll see.

**Comment by bmartinez287** [comment]
that's cool, I imagine you used an organizational token instead of a personal one.
Lets try it.

**Pull request merged**
