### PR TITLE
GitHub style for inline code blocks

### PR DESCRIPTION
**Pull request by stasadev**
## The Issue

I have a hard time telling if I'm looking at the code or something else.

## How This PR Solves The Issue

Use style similar to GitHub.

## Manual Testing Instructions

Example from https://ddev.com/blog/anatomy-advanced-ddev-addon/

Before:
image

After:
image

Before:
image

After:
image

### CODE REVIEW

**Comment by rfay** [comment]
You say 
> Bring back the backticks

Does that mean there is a history to this?

**Comment by stasadev** [comment]
See the change, Tailwind CSS adds backticks by default to the `<code></code>` blocks.
And these backticks were removed while developing this website.

**Comment by rfay** [comment]
I can see why it was done, as the backticks are "literal", whereas in markdown we would never see them. With this change, we see them. As with markdown, backticks are part of the source, not part of the presentation.

image

**Comment by stasadev** [comment]
The reason why I want to bring them back is that the markdown command is not always clearly visible, it just blends in with the rest of the text (I can see it's just bolder text and that's it).

I just want to emphasize these blocks of code somehow, not necessarily with backticks, another idea would be to add a background like here on GitHub.

**Comment by rfay** [comment]
That's completely opposite how markdown works, which is where the backticks idea comes from. In markdown the *source* has backticks, but the presentation does not, instead it has styled text.

I think perhaps what you want is different styling for these presentations? Maybe you like the github markdown styling better?

**Comment by stasadev** [comment]
> I think perhaps what you want is different styling for these presentations? Maybe you like the github markdown styling better?

Yes, that's what I want.

I investigated Tailwind config, and made necessary changes.
Please check the before/after in the first post.

**Comment by rfay** [comment]
I sure like how it looks! https://20240903-stasadev-code-backt.ddev-com-front-end.pages.dev/blog/anatomy-advanced-ddev-addon/

**Review by rfay — APPROVED** [review]
Looks fantastic to me, thanks!

**Pull request merged**
